//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebTest1Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ideas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ideas()
        {
            this.Interactive = new HashSet<Interactive>();
            this.LikeDislike = new HashSet<LikeDislike>();
            this.Replies = new HashSet<Replies>();
        }
    
        public int ideaID { get; set; }
        public string ideaTitle { get; set; }
        public System.DateTime creatAt { get; set; }
        public byte[] fileI { get; set; }
        public string urlFile { get; set; }
        public string description { get; set; }
        public Nullable<int> categoryID { get; set; }
        public int likes { get; set; }
        public int dislikes { get; set; }
        public string Iname { get; set; }
        public string incognito { get; set; }
        public int CountViews { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interactive> Interactive { get; set; }
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeDislike> LikeDislike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Replies> Replies { get; set; }
    }
}
