//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebTest1Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interactive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interactive()
        {
            this.Replies = new HashSet<Replies>();
        }
    
        public int interactiveID { get; set; }
        public Nullable<System.DateTime> createOn { get; set; }
        public string comment { get; set; }
        public Nullable<int> ideaID { get; set; }
        public string Cname { get; set; }
        public string incognito { get; set; }
    
        public virtual Ideas Ideas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Replies> Replies { get; set; }
    }
}
