//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebTest1Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeDislike
    {
        public int likeDislikeID { get; set; }
        public Nullable<int> ideaID { get; set; }
        public string IsAction { get; set; }
        public string UserAction { get; set; }
    
        public virtual Ideas Ideas { get; set; }
    }
}
