//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebTest1Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Replies
    {
        public int repliesID { get; set; }
        public Nullable<System.DateTime> createOn { get; set; }
        public string comment { get; set; }
        public string Rname { get; set; }
        public Nullable<int> interactiveID { get; set; }
        public Nullable<int> ideaID { get; set; }
    
        public virtual Interactive Interactive { get; set; }
        public virtual Ideas Ideas { get; set; }
    }
}
