//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebTest1Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_d
    {
        public int ideaID { get; set; }
        public string Title { get; set; }
        public Nullable<int> TotalLikes { get; set; }
        public Nullable<int> TotalComments { get; set; }
        public Nullable<int> TotalInteract { get; set; }
    }
}
