//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMWebTest1Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_e
    {
        public int ideaID { get; set; }
        public string ideaTitle { get; set; }
        public System.DateTime creatAt { get; set; }
        public byte[] fileI { get; set; }
        public string urlFile { get; set; }
        public string description { get; set; }
        public Nullable<int> categoryID { get; set; }
        public int likes { get; set; }
        public int dislikes { get; set; }
        public string Iname { get; set; }
        public string incognito { get; set; }
        public int CountViews { get; set; }
    }
}
